<?php
/**
 * @file
 * Code for the HumanitarianResponse Clusters Menu feature.
 */

include_once 'humanitarianresponse_clusters_menu.features.inc';

/**
 * Implements hook_feeds_after_import()
 */
function humanitarianresponse_clusters_menu_feeds_after_import(FeedsSource $source) {
  if ($source->id == 'csv_clusters') {
    // Rebuild taxonomy menu
    $voc = taxonomy_vocabulary_machine_name_load('clusters');
    $vid = $voc->vid;
    _taxonomy_menu_rebuild($vid);
  }
}
